export const colors = {
	blue: [
		'var(--color-base-blue-50)',
		'var(--color-base-blue-100)',
		'var(--color-base-blue-200)',
		'var(--color-base-blue-300)',
		'var(--color-base-blue-400)',
		'var(--color-base-blue-500)',
		'var(--color-base-blue-600)',
		'var(--color-base-blue-700)',
		'var(--color-base-blue-800)',
		'var(--color-base-blue-900)',
	] as const,
	brown: [
		'var(--color-base-brown-50)',
		'var(--color-base-brown-100)',
		'var(--color-base-brown-200)',
		'var(--color-base-brown-300)',
		'var(--color-base-brown-400)',
		'var(--color-base-brown-500)',
		'var(--color-base-brown-600)',
		'var(--color-base-brown-700)',
		'var(--color-base-brown-800)',
		'var(--color-base-brown-900)',
	] as const,
	beige: [
		'var(--color-base-beige-50)',
		'var(--color-base-beige-100)',
		'var(--color-base-beige-200)',
		'var(--color-base-beige-300)',
		'var(--color-base-beige-400)',
		'var(--color-base-beige-500)',
		'var(--color-base-beige-600)',
		'var(--color-base-beige-700)',
		'var(--color-base-beige-800)',
		'var(--color-base-beige-900)',
	] as const,
	sand: [
		'var(--color-base-sand-50)',
		'var(--color-base-sand-100)',
		'var(--color-base-sand-200)',
		'var(--color-base-sand-300)',
		'var(--color-base-sand-400)',
		'var(--color-base-sand-500)',
		'var(--color-base-sand-600)',
		'var(--color-base-sand-700)',
		'var(--color-base-sand-800)',
		'var(--color-base-sand-900)',
	] as const,
	orange: [
		'var(--color-base-orange-50)',
		'var(--color-base-orange-100)',
		'var(--color-base-orange-200)',
		'var(--color-base-orange-300)',
		'var(--color-base-orange-400)',
		'var(--color-base-orange-500)',
		'var(--color-base-orange-600)',
		'var(--color-base-orange-700)',
		'var(--color-base-orange-800)',
		'var(--color-base-orange-900)',
	] as const,
	red: [
		'var(--color-base-red-50)',
		'var(--color-base-red-100)',
		'var(--color-base-red-200)',
		'var(--color-base-red-300)',
		'var(--color-base-red-400)',
		'var(--color-base-red-500)',
		'var(--color-base-red-600)',
		'var(--color-base-red-700)',
		'var(--color-base-red-800)',
		'var(--color-base-red-900)',
	] as const,
	gray: [
		'var(--color-base-gray-50)',
		'var(--color-base-gray-100)',
		'var(--color-base-gray-200)',
		'var(--color-base-gray-300)',
		'var(--color-base-gray-400)',
		'var(--color-base-gray-500)',
		'var(--color-base-gray-600)',
		'var(--color-base-gray-700)',
		'var(--color-base-gray-800)',
		'var(--color-base-gray-900)',
	] as const,
};
