import './globals.css';
import '@mantine/core/styles.css';
import { Inter } from 'next/font/google'
import { MantineProvider } from '@mantine/core';
import { theme } from '@/theme';

if (process.env.NEXT_RUNTIME === 'nodejs') {
    const { server } = require('../mocks/node')
    server.listen()
}

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}:{children: React.ReactNode}) {
  return (
    <html lang="en">
        <body className={inter.className}>
            <MantineProvider theme={theme}>
                {children}
            </MantineProvider>
        </body>
    </html>
  )
}
